const data = {
    products:[
        {
            _id:'1',
            name:'Amigurumi Elephant',
            category: 'Toys',
            image: '/images/p1.jpg',
            price: 30,
            brand: 'Amigurumi',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'Amigurumi Duck',
            category: 'Toys',
            image: '/images/p2.jpg',
            price: 20,
            brand: 'Amigurumi',
            rating:5,
            numReviews:12,
            description: 'high quality product',
        },
        {
            _id:'3',
            name:'Amigurumi Whale',
            category: 'Toys',
            image: '/images/p3.jpg',
            price: 15,
            brand: 'Amigurumi',
            rating:4,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Amigurumi Turtle',
            category: 'Toys',
            image: '/images/p4.jpg',
            price: 25,
            brand: 'Amigurumi',
            rating:5,
            numReviews:8,
            description: 'high quality product',
        },
        {
            _id:'5',
            name:'Amigurumi Jellyfish',
            category: 'Toys',
            image: '/images/p5.jpg',
            price: 30,
            brand: 'Amigurumi',
            rating:5,
            numReviews:16,
            description: 'high quality product',
        },
        {
            _id:'6',
            name:'Amigurumi Penguin',
            category: 'Toys',
            image: '/images/p6.jpg',
            price: 25,
            brand: 'Amigurumi',
            rating:4,
            numReviews:22,
            description: 'high quality product',
        },
    ],
};
export default data;